In [1]:
import numpy as np
from numpy import linalg as LA

## Vectors

In [2]:
v1 = np.array([1,2,3])
v2 = np.array([1,2,3])

In [3]:
np.dot(v1,v2)

14

In [6]:
v1@v2

14

In [4]:
v1 + v2

array([2, 4, 6])

In [5]:
v1*v2

array([1, 4, 9])

In [8]:
2*v1

array([2, 4, 6])

## Metrices

In [7]:
m1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
m2 = np.array([[1,2],[3,4],[5,6]])

In [27]:
m1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
m1.shape

(3, 3)

In [29]:
m1.size

9

In [30]:
m1.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [8]:
m1@m2

array([[ 22,  28],
       [ 49,  64],
       [ 76, 100]])

In [9]:
np.dot(m1,m2)

array([[ 22,  28],
       [ 49,  64],
       [ 76, 100]])

In [11]:
m1*m1

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])