In [1]:
from sklearn import datasets
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn import preprocessing
from sklearn import metrics
import numpy as np
import pandas as pd

In [ ]:
x,y = datasets.load_boston(return_X_y=True)

In [ ]:
print(x.shape)
print(y.shape)

(506, 13)
(506,)


In [ ]:
dataset = datasets.load_boston()

In [ ]:
x = dataset.data
y = dataset.target

In [ ]:
print(x.shape)
print(y.shape)

(506, 13)
(506,)


## Reading data from a local file

In [ ]:
data1 = np.loadtxt('simpleregression.txt')

In [ ]:
x = data1[:,:-1]
y = data1[:,-1]

In [ ]:
data2 = pd.read_csv('winequality.csv')

In [ ]:
data2.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [ ]:
x = data2.values[:,:-1]
x

array([[ 7.4  ,  0.7  ,  0.   , ...,  3.51 ,  0.56 ,  9.4  ],
       [ 7.8  ,  0.88 ,  0.   , ...,  3.2  ,  0.68 ,  9.8  ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  3.26 ,  0.65 ,  9.8  ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  3.42 ,  0.75 , 11.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  3.57 ,  0.71 , 10.2  ],
       [ 6.   ,  0.31 ,  0.47 , ...,  3.39 ,  0.66 , 11.   ]])

In [ ]:
y = data2.values[:,-1]
y

array([5., 5., 5., ..., 6., 5., 6.])

In [ ]:
x = preprocessing.MinMaxScaler().fit_transform(x)
x

array([[0.24778761, 0.39726027, 0.        , ..., 0.60629921, 0.13772455,
        0.15384615],
       [0.28318584, 0.52054795, 0.        , ..., 0.36220472, 0.20958084,
        0.21538462],
       [0.28318584, 0.43835616, 0.04      , ..., 0.40944882, 0.19161677,
        0.21538462],
       ...,
       [0.15044248, 0.26712329, 0.13      , ..., 0.53543307, 0.25149701,
        0.4       ],
       [0.11504425, 0.35958904, 0.12      , ..., 0.65354331, 0.22754491,
        0.27692308],
       [0.12389381, 0.13013699, 0.47      , ..., 0.51181102, 0.19760479,
        0.4       ]])

## Applying ML models with your data

In [ ]:
lr = LinearRegression(fit_intercept=True)
ridge = Ridge(alpha = 0.5)

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.5,random_state=0)

In [ ]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(253, 13)
(253, 13)
(253,)
(253,)


In [ ]:
lr.fit(x_train, y_train)
ridge.fit(x_train, y_train)

Ridge(alpha=0.5)

In [ ]:
predictionsLR = lr.predict(x_test)
print(predictionsLR)
print(mean_absolute_error(predictionsLR, y_test))

[24.70960325 25.12631354 30.76503263 12.41405512 21.29599499 18.9820552
 21.41132996 20.67952823 19.00064129 20.20283837  5.56400169 16.92323348
 17.51322896  5.16858442 42.95215092 32.9806573  23.36140299 37.62826682
 31.09206869 22.89283336 24.57289742 25.81536634 20.26467062 30.79131551
 21.95868456 11.79141163 16.88663056 19.19534708 35.40278965 20.65291048
 18.68119761 18.36807058 19.23453044 23.58815977 29.06218826 21.12413253
 10.68515822 27.15483771 18.39065879 15.3858284  26.49125897 19.99603848
 21.88280039 16.08194711 22.40800324 24.76641999 19.58660105 24.79000679
  9.59564604 24.21884557 23.12098756 16.80153308 24.24031563 29.42927442
 13.851603   21.15932546 20.39800177 14.21419815 15.6911474  22.4954085
 17.15556137 21.23238059 33.42098655 31.5832431  18.3631319  33.63873423
 19.03143924 18.53466863 19.51152135 22.78181836 23.02677155 24.29954349
 31.56802819 29.23584248 27.05755582  4.38763735 36.91142859 23.52551148
 26.99615168 19.06117058 28.61936286 19.70539962 20.2

In [ ]:
predictionsR = ridge.predict(x_test)
print(predictionsR)
print(mean_absolute_error(predictionsR,y_test))

[24.80360943 24.73539403 30.39780122 12.40553362 20.79803971 19.40388955
 21.18214301 20.99565887 19.02426418 19.99879681  5.36368389 16.21808903
 17.93509271  5.05178706 42.65517908 32.94679998 22.78240002 37.37457445
 31.20174003 23.01044247 24.69486913 25.35061009 20.08583937 30.62107128
 21.81051138 11.07453103 17.03360027 20.36448845 35.19824057 20.31916718
 18.27284982 18.76847174 19.03135313 23.14224138 28.75382621 21.69617143
 10.68363849 26.98612597 17.74210481 14.72099602 26.10056456 19.84916569
 21.91301663 15.41364384 22.76364783 24.53280879 18.95001075 26.00977557
 10.66191027 24.22559263 24.34162346 17.26895079 23.97355545 30.04081602
 13.86711888 21.24051043 20.35188734 14.30903014 14.90674153 21.97960649
 17.58350061 21.40501834 33.26780334 31.69113278 18.02957703 33.33149629
 19.33748019 18.37075237 18.88335454 22.80962814 22.29273219 23.82481841
 31.36615247 29.65358093 26.46411679  4.37177305 36.91933075 23.43689537
 26.88842557 19.28277885 28.38138273 19.80757983 19