In [1]:
import numpy as np
from sklearn import metrics

## Perceptron

In [2]:
X = np.array([[2.5, -3], [-1, 0.5], [0, -1.5]])

#### Binary step activation function

In [8]:
def step_binary(v):
    return 1*(v>0)

In [9]:
step_binary(2)

1

In [10]:
step_binary(np.array([-1,1]))

array([0, 1])

In [11]:
step_binary(X)

array([[1, 0],
       [0, 1],
       [0, 0]])

#### Single Neuron

In [12]:
def perceptron(x,w,b):
    in_ = x@w + b
    out = step_binary(in_)
    return out

Initializing weights and bias

In [13]:
w = np.array([[-0.2],[0.7]])
b = 0

Running perceptron for a single instance (i.e. the input to the perceptron is a single vector)

In [14]:
for i in range(X.shape[0]):
    print("input: ",X[i], ",output: ", perceptron(X[i], w, b))

input:  [ 2.5 -3. ] ,output:  [0]
input:  [-1.   0.5] ,output:  [1]
input:  [ 0.  -1.5] ,output:  [0]


Running perceptron for a set of instances (batch) - the input to the perceptron is a matrix

In [15]:
print(perceptron(X,w,b))

[[0]
 [1]
 [0]]


## Using bigger datasets

In [21]:
from sklearn import preprocessing
data = np.loadtxt("diabetes_binary_classification.txt")

# split into inputs and outputs
X, y = data[:, :-1], data[:, -1]

print ("X shape:", X.shape)
print ("y shape:", y.shape)

X shape: (768, 8)
y shape: (768,)


Initialising parameters from a uniform distribution over [-1, 1)

In [17]:
np.random.seed(0)
w = np.random.uniform(-1,1,[X.shape[1],1])
b = np.random.uniform(-1,1,1)

In [18]:
w

array([[ 0.09762701],
       [ 0.43037873],
       [ 0.20552675],
       [ 0.08976637],
       [-0.1526904 ],
       [ 0.29178823],
       [-0.12482558],
       [ 0.783546  ]])

Passing through the network

In [22]:
predictions = perceptron(X,w,b)
print(predictions.shape)

(768, 1)


Evaluating the performance

In [23]:
y = y.reshape(len(y),1)
print('MSE: ', metrics.mean_squared_error(predictions,y))
print('Accuracy:', metrics.accuracy_score(predictions,y))
print('F1:', metrics.f1_score(predictions,y))

MSE:  0.6510416666666666
Accuracy: 0.3489583333333333
F1: 0.5173745173745173


## Simple Update Rule

In [24]:
def updateRule(X,y,lr):
    np.random.seed(0)
    w = np.random.uniform(-1,1,[X.shape[1],1])
    b = np.random.uniform(-1,1,1)
    
    for k in range(100):
        for i in range(len(X)):
            prediction = perceptron(X[i], w, b)
            error = y[i]-prediction
            w += lr * error * X[i].reshape(len(X[i]),1)
            b += lr*error
    
    #Calculating predictions
    predictions = perceptron(X,w, b)
    #Calculating error
    print('MSE: ', metrics.mean_squared_error(predictions,y))
    print('Accuracy:', metrics.accuracy_score(predictions,y))
    print('F1:', metrics.f1_score(predictions,y))

In [25]:
updateRule(X,y,0.05) 

MSE:  0.3424479166666667
Accuracy: 0.6575520833333334
F1: 0.41942604856512145
